name: gymrat
description: "GymRat - gamified fitness app."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.13.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  crypto: ^3.0.6
  purchases_flutter: ^10.10.1
  shared_preferences: ^2.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/characters/male/
    - assets/characters/male/level_01/idle/
    - assets/characters/male/level_01/blink/
    - assets/characters/male/level_01/tail/
    - assets/characters/male/level_01_back/idle/
    - assets/characters/male/motion/level_01/front/
    - assets/characters/male/motion/level_01/back/
    - assets/characters/female/
    - assets/characters/female/level_01/idle/
    - assets/characters/female/level_01/blink/
    - assets/characters/female/level_01/tail/
    - assets/characters/female/level_01_back/idle/
    - assets/characters/female/motion/level_01/front/
    - assets/characters/female/motion/level_01/back/
    - assets/characters/non_binary/
    - assets/characters/non_binary/level_01/idle/
    - assets/characters/non_binary/level_01/blink/
    - assets/characters/non_binary/level_01/tail/
    - assets/characters/non_binary/level_01_back/idle/
    - assets/characters/non_binary/motion/level_01/front/
    - assets/characters/non_binary/motion/level_01/back/
    - assets/gyms/
    - assets/items/
    - assets/effects/
