import 'package:flutter/material.dart';

class GymRatLocalizations {
  GymRatLocalizations(this.locale);
  final Locale locale;
  static GymRatLocalizations of(BuildContext context) =>
      Localizations.of<GymRatLocalizations>(context, GymRatLocalizations)!;
  static const delegate = _GymRatLocalizationsDelegate();
  static const _values = <String, Map<String, String>>{
    'en': {
      'workout': 'Workout',
      'progress': 'Progress',
      'history': 'History',
      'nutrition': 'Nutrition',
      'inventoryShop': 'Gym Armory',
      'missions': 'Missions',
      'armoryTitle': 'GYM ARMORY',
      'armoryCollection': 'COLLECTION',
      'armoryStore': 'STORE',
      'armoryLoadError': 'The Armory could not be loaded.',
      'armoryCollectionTitle': 'YOUR GYM. YOUR LEGACY.',
      'armoryCollectionSubtitle':
          'Every upgrade here was earned through training.',
      'armoryUnlockedCount': 'UPGRADES UNLOCKED',
      'armoryEarnedUpgrades': 'EARNED GYM UPGRADES',
      'armoryNext': 'NEXT AT LEVEL',
      'armoryComplete': 'ARMORY COMPLETE',
      'armoryVaultTitle': 'THE PREMIUM VAULT',
      'armoryVaultSubtitle': 'Premium and cosmetic rat items will appear here from the official store.',
      'restorePurchases': 'RESTORE PURCHASES',
      'armoryOwned': 'OWNED',
      'armoryStorePreparing': 'THE VAULT IS BEING FORGED',
      'armoryStorePreparingMessage': 'Your earned collection is ready. Store items activate when official products are connected.',
      'armoryStoreEmpty': 'NO ITEMS IN THIS DROP',
      'armoryStoreEmptyMessage':
          'The store is connected, but no current offering is available.',
      'armoryStoreUnavailable': 'THE VAULT IS OFFLINE',
      'armoryStoreUnavailableMessage': 'Store items could not be loaded. Your training progress is unaffected.',
      'armoryPurchaseComplete': 'Item unlocked in your account.',
      'armoryPurchaseFailed': 'The purchase could not be completed.',
      'armoryRestoreComplete': 'Purchases restored.',
      'armoryRestoreFailed': 'Purchases could not be restored.',
      'questBoardTitle': 'QUEST BOARD',
      'questBoardSubtitle': 'Train today and finish your daily contracts.',
      'questLoadError': 'Missions could not be loaded.',
      'dailyContracts': 'DAILY CONTRACTS',
      'dailyContractsSubtitle': 'Resets with each new day.',
      'weeklyCampaign': 'WEEKLY CAMPAIGN',
      'weeklyCampaignSubtitle': 'Build momentum from Monday to Sunday.',
      'questsInProgress': 'CONTRACTS IN PROGRESS',
      'dailyComplete': 'DAILY BOARD CLEARED',
      'dailyCompleteMessage': 'Every daily contract is complete. Strong work.',
      'questDailySession': 'ANSWER THE CALL',
      'questDailySessionDescription': 'Complete one workout or walk today.',
      'questDailyDuration': 'HOLD THE LINE',
      'questDailyDurationDescription': 'Train for 20 minutes today.',
      'questDailyExercises': 'CLEAR THE RACK',
      'questDailyExercisesDescription': 'Complete three exercises today.',
      'questWeeklySessions': 'THREE-BATTLE CAMPAIGN',
      'questWeeklySessionsDescription': 'Complete three sessions this week.',
      'questWeeklyDuration': 'ENDURANCE CAMPAIGN',
      'questWeeklyDurationDescription': 'Train for 90 minutes this week.',
      'profileSettings': 'Profile & Settings',
      'premium': 'GymRat Premium',
      'startWorkout': 'START WORKOUT',
      'chooseSession': 'CHOOSE YOUR\nSESSION',
      'workoutTagline': 'Train. Earn XP. Level up.',
      'workoutTitle': 'WORKOUT',
      'timedWalkStreak': 'Timed walk · counts toward your streak',
      'customWorkout': 'CUSTOM WORKOUT',
      'customWorkoutDescription':
          'Build your own session from the full exercise library.',
      'premiumLabel': 'PREMIUM',
      'preview': 'PREVIEW',
      'startWalk': 'START WALK',
      'sets': 'SETS',
      'timedWalk': 'TIMED WALK',
      'timedWalkDescription': 'Walk for as long as you want. The session counts toward your streak.',
      'walkTitle': 'WALK',
      'walkInProgress': 'WALK IN PROGRESS',
      'ready': 'READY',
      'pause': 'PAUSE',
      'start': 'START',
      'saving': 'SAVING...',
      'finish': 'FINISH',
      'exercise': 'EXERCISE',
      'addSet': 'ADD SET',
      'totalVolume': 'TOTAL VOLUME',
      'setLabel': 'SET',
      'rest': 'REST',
      'reps': 'REPS',
      'finishWorkout': 'FINISH WORKOUT',
      'nextExercise': 'NEXT EXERCISE',
      'timerSettings': 'TIMER SETTINGS',
      'save': 'SAVE',
      'setTimer': 'SET TIMER',
      'restTimer': 'REST TIMER',
      'autoLoop': 'AUTO LOOP',
      'autoLoopDescription': 'Automatically switch between set and rest.',
      'progressTitle': 'PROGRESS',
      'progressComingSoon': 'Levels, XP and progression come next.',
      'totalXp': 'TOTAL XP',
      'totalWorkouts': 'WORKOUTS',
      'recentWorkouts': 'RECENT WORKOUTS',
      'noWorkoutsYet': 'Complete your first workout to start your history.',
      'nextLevel': 'NEXT LEVEL',
      'minutesShort': 'MIN',
      'progressLoadError': 'Progress could not be loaded.',
      'historyLoadError': 'Training history could not be loaded.',
      'trainingHistory': 'TRAINING HISTORY',
      'combatLog': 'COMBAT LOG',
      'records': 'RECORDS',
      'trainingArchive': 'TRAINING ARCHIVE',
      'trainingArchiveSubtitle': 'Every session is proof of the work.',
      'emptyHistoryTitle': 'NO BATTLES LOGGED',
      'emptyHistoryMessage': 'Complete a workout to write the first entry.',
      'tapForDetails': 'TAP FOR DETAILS',
      'workoutDetails': 'WORKOUT DETAILS',
      'exerciseBreakdown': 'EXERCISE BREAKDOWN',
      'noExercisesRecorded': 'No exercises recorded for this session.',
      'recordVault': 'HALL OF RECORDS',
      'recordVaultSubtitle': 'Earned under pressure. Built one rep at a time.',
      'recordsUnlocked': 'RECORDS UNLOCKED',
      'noRecordsTitle': 'NO RECORDS YET',
      'noRecordsMessage':
          'Your first result sets the baseline. Beat it to unlock a record.',
      'baseline': 'BASELINE',
      'previousBest': 'PREVIOUS BEST',
      'totalGain': 'TOTAL GAIN',
      'recordBreaks': 'RECORD BREAKS',
      'language': 'Language',
      'systemDefault': 'System default',
      'english': 'English',
      'swedish': 'Swedish',
      'spanish': 'Spanish',
      'russian': 'Russian',
      'chinese': 'Chinese',
      'settings': 'SETTINGS',
      'appLanguage': 'APP LANGUAGE',
      'languageHelp': 'GymRat uses your phone language by default.',
      'level': 'LVL',
      'days': 'DAYS',
      'day': 'DAY',
      'xp': 'XP',
      'soon': 'SOON',
      'personalBest': 'PERSONAL BEST',
      'newPersonalBest': 'NEW PERSONAL BEST',
      'levelUp': 'LEVEL UP!',
      'workoutComplete': 'WORKOUT COMPLETE',
      'xpEarned': 'XP EARNED',
      'streak': 'STREAK',
      'volume': 'VOLUME',
      'time': 'TIME',
      'collectContinue': 'COLLECT XP & CONTINUE',
      'evolutionUnlocked': 'GYMRAT EVOLUTION UNLOCKED',
      'recordBroken': 'RECORD BROKEN',
      'powerSurging': 'POWER SURGING',
      'gymUpgrade': 'GYM UPGRADE',
      'unlocked': 'UNLOCKED',
      'tier': 'TIER',
      'upgradeDumbbellRack': 'STEEL DUMBBELL RACK',
      'upgradeNeonLights': 'NEON POWER LIGHTS',
      'upgradeWeightPlates': 'OLYMPIC WEIGHT PLATES',
      'upgradePowerRack': 'POWER RACK',
      'upgradeLiftingPlatform': 'ELITE LIFTING PLATFORM',
      'upgradeBanner': 'GYMRAT BATTLE BANNER',
      'upgradeSpotlights': 'CHAMPION SPOTLIGHTS',
      'upgradeSpeakers': 'HEAVY SOUND SYSTEM',
      'upgradeChampionPlaque': 'CHAMPION PLAQUE',
      'upgradeCableTowers': 'ELITE CABLE TOWERS',
      'upgradeKettlebellRack': 'KETTLEBELL RACK',
      'upgradeChalkStation': 'CHALK STATION',
      'upgradeBattleRopes': 'BATTLE ROPES',
      'upgradePlyoBoxes': 'PLYOMETRIC BOXES',
      'upgradeWallArmor': 'GRAPHITE WALL ARMOR',
      'upgradeAirBike': 'AIR BIKE',
      'upgradeRower': 'ROWING ERGOMETER',
      'upgradeProwlerSled': 'PROWLER SLED',
      'upgradeClimbingRopes': 'CLIMBING ROPES',
      'upgradeLightingTruss': 'ELITE LIGHTING TRUSS',
      'upgradeTrophyCase': 'TROPHY CASE',
      'upgradePunchingBag': 'HEAVY PUNCHING BAG',
      'upgradeLegPress': 'LEG PRESS',
      'upgradeGluteHam': 'GLUTE-HAM STATION',
      'upgradeLightningInsignia': 'GYMRAT LIGHTNING INSIGNIA',
      'upgradeMedicineBallRack': 'MEDICINE BALL RACK',
      'upgradeResistanceStation': 'RESISTANCE BAND STATION',
      'upgradeLandmineStation': 'LANDMINE STATION',
      'upgradeRecoveryFan': 'RECOVERY FAN',
      'upgradeCompetitionPlatform': 'COMPETITION PLATFORM',
      'upgradeCurvedTreadmill': 'CURVED TREADMILL',
      'upgradeSkiErg': 'SKIERG',
      'upgradeChainStorage': 'HEAVY CHAIN STORAGE',
      'upgradeSpecialtyBars': 'SPECIALTY BAR RACK',
      'upgradeChampionColumns': 'CHAMPION COLUMNS',
      'upgradeAtlasStones': 'ATLAS STONES',
      'upgradeFarmerHandles': 'FARMER CARRY HANDLES',
      'upgradeYoke': 'STRONGMAN YOKE',
      'upgradeDustExtraction': 'CHALK DUST EXTRACTION',
      'upgradeChampionDisplay': 'CHAMPION DISPLAY',
      'upgradeDipStation': 'WEIGHTED DIP STATION',
      'upgradeReverseHyper': 'REVERSE HYPER',
      'upgradeLegExtension': 'LEG EXTENSION & CURL',
      'upgradeCalfRaise': 'STANDING CALF RAISE',
      'upgradePrestigeLighting': 'PRESTIGE LIGHTING',
      'upgradeMonolift': 'COMPETITION MONOLIFT',
      'upgradeCompetitionBench': 'COMPETITION BENCH',
      'upgradeDeadliftStation': 'DEADLIFT SERVICE STATION',
      'upgradeRecoveryStation': 'ELITE RECOVERY STATION',
      'upgradeVictoryArch': 'CHAMPIONSHIP VICTORY ARCH',
    },
    'sv': {
      'workout': 'Träning',
      'progress': 'Utveckling',
      'history': 'Historik',
      'nutrition': 'Kost',
      'inventoryShop': 'Gym Armory',
      'missions': 'Uppdrag',
      'armoryTitle': 'GYM ARMORY',
      'armoryCollection': 'SAMLING',
      'armoryStore': 'BUTIK',
      'armoryLoadError': 'Gym Armory kunde inte läsas in.',
      'armoryCollectionTitle': 'DITT GYM. DITT ARV.',
      'armoryCollectionSubtitle':
          'Varje uppgradering här har förtjänats genom träning.',
      'armoryUnlockedCount': 'UPPLÅSTA UPPGRADERINGAR',
      'armoryEarnedUpgrades': 'FÖRTJÄNADE GYMUPPGRADERINGAR',
      'armoryNext': 'NÄSTA PÅ NIVÅ',
      'armoryComplete': 'ARMORY KOMPLETT',
      'armoryVaultTitle': 'PREMIUMVALVET',
      'armoryVaultSubtitle': 'Premium och kosmetiska rått-items visas här från den officiella butiken.',
      'restorePurchases': 'ÅTERSTÄLL KÖP',
      'armoryOwned': 'ÄGS',
      'armoryStorePreparing': 'VALVET SMIDS',
      'armoryStorePreparingMessage': 'Din förtjänade samling är klar. Butiksitems aktiveras när officiella produkter ansluts.',
      'armoryStoreEmpty': 'INGA ITEMS I DENNA DROP',
      'armoryStoreEmptyMessage':
          'Butiken är ansluten, men inget aktuellt erbjudande finns.',
      'armoryStoreUnavailable': 'VALVET ÄR OFFLINE',
      'armoryStoreUnavailableMessage': 'Butiksitems kunde inte läsas in. Din träningsprogression påverkas inte.',
      'armoryPurchaseComplete': 'Itemet har låsts upp på ditt konto.',
      'armoryPurchaseFailed': 'Köpet kunde inte slutföras.',
      'armoryRestoreComplete': 'Köpen har återställts.',
      'armoryRestoreFailed': 'Köpen kunde inte återställas.',
      'questBoardTitle': 'UPPDRAGSTAVLA',
      'questBoardSubtitle': 'Träna idag och slutför dina dagliga kontrakt.',
      'questLoadError': 'Uppdragen kunde inte läsas in.',
      'dailyContracts': 'DAGLIGA KONTRAKT',
      'dailyContractsSubtitle': 'Återställs vid varje ny dag.',
      'weeklyCampaign': 'VECKOKAMPANJ',
      'weeklyCampaignSubtitle': 'Bygg momentum från måndag till söndag.',
      'questsInProgress': 'PÅGÅENDE KONTRAKT',
      'dailyComplete': 'DAGENS TAVLA RENSAD',
      'dailyCompleteMessage': 'Alla dagliga kontrakt är klara. Starkt jobbat.',
      'questDailySession': 'SVARA PÅ KALLET',
      'questDailySessionDescription':
          'Slutför ett pass eller en promenad idag.',
      'questDailyDuration': 'HÅLL LINJEN',
      'questDailyDurationDescription': 'Träna i 20 minuter idag.',
      'questDailyExercises': 'RENSA STÄLLET',
      'questDailyExercisesDescription': 'Slutför tre övningar idag.',
      'questWeeklySessions': 'TRESTRIDSKAMPANJ',
      'questWeeklySessionsDescription': 'Slutför tre pass den här veckan.',
      'questWeeklyDuration': 'UTHÅLLIGHETSKAMPANJ',
      'questWeeklyDurationDescription': 'Träna i 90 minuter den här veckan.',
      'profileSettings': 'Profil & Inställningar',
      'premium': 'GymRat Premium',
      'startWorkout': 'STARTA TRÄNING',
      'chooseSession': 'VÄLJ DITT\nPASS',
      'workoutTagline': 'Träna. Tjäna XP. Gå upp i nivå.',
      'workoutTitle': 'TRÄNING',
      'timedWalkStreak': 'Tidsinställd promenad · räknas mot din svit',
      'customWorkout': 'ANPASSAT PASS',
      'customWorkoutDescription':
          'Bygg ditt eget pass från hela övningsbiblioteket.',
      'premiumLabel': 'PREMIUM',
      'preview': 'FÖRHANDSVISNING',
      'startWalk': 'STARTA PROMENAD',
      'sets': 'SET',
      'timedWalk': 'TIDSINSTÄLLD PROMENAD',
      'timedWalkDescription':
          'Gå så länge du vill. Passet räknas mot din svit.',
      'walkTitle': 'PROMENAD',
      'walkInProgress': 'PROMENAD PÅGÅR',
      'ready': 'REDO',
      'pause': 'PAUSA',
      'start': 'STARTA',
      'saving': 'SPARAR...',
      'finish': 'SLUTFÖR',
      'exercise': 'ÖVNING',
      'addSet': 'LÄGG TILL SET',
      'totalVolume': 'TOTAL VOLYM',
      'setLabel': 'SET',
      'rest': 'VILA',
      'reps': 'REPS',
      'finishWorkout': 'AVSLUTA PASS',
      'nextExercise': 'NÄSTA ÖVNING',
      'timerSettings': 'TIMERINSTÄLLNINGAR',
      'save': 'SPARA',
      'setTimer': 'SETTIMER',
      'restTimer': 'VILOTIMER',
      'autoLoop': 'AUTOMATISK VÄXLING',
      'autoLoopDescription': 'Växla automatiskt mellan set och vila.',
      'progressTitle': 'UTVECKLING',
      'progressComingSoon': 'Nivåer, XP och progression kommer härnäst.',
      'totalXp': 'TOTAL XP',
      'totalWorkouts': 'PASS',
      'recentWorkouts': 'SENASTE PASSEN',
      'noWorkoutsYet': 'Slutför ditt första pass för att starta historiken.',
      'nextLevel': 'NÄSTA NIVÅ',
      'minutesShort': 'MIN',
      'progressLoadError': 'Utvecklingen kunde inte läsas in.',
      'historyLoadError': 'Träningshistoriken kunde inte läsas in.',
      'trainingHistory': 'TRÄNINGSHISTORIK',
      'combatLog': 'KAMPLOGG',
      'records': 'REKORD',
      'trainingArchive': 'TRÄNINGSARKIV',
      'trainingArchiveSubtitle': 'Varje pass är bevis på arbetet.',
      'emptyHistoryTitle': 'INGA PASS REGISTRERADE',
      'emptyHistoryMessage':
          'Slutför ett pass för att skriva den första posten.',
      'tapForDetails': 'TRYCK FÖR DETALJER',
      'workoutDetails': 'PASSDETALJER',
      'exerciseBreakdown': 'ÖVNINGSDETALJER',
      'noExercisesRecorded': 'Inga övningar registrerades för detta pass.',
      'recordVault': 'REKORDHALLEN',
      'recordVaultSubtitle':
          'Förtjänat under press. Byggt en repetition i taget.',
      'recordsUnlocked': 'UPPLÅSTA REKORD',
      'noRecordsTitle': 'INGA REKORD ÄN',
      'noRecordsMessage': 'Ditt första resultat sätter baslinjen. Slå det för att låsa upp ett rekord.',
      'baseline': 'BASLINJE',
      'previousBest': 'FÖREGÅENDE REKORD',
      'totalGain': 'TOTAL ÖKNING',
      'recordBreaks': 'REKORDSLAGNINGAR',
      'language': 'Språk',
      'systemDefault': 'Systemspråk',
      'english': 'Engelska',
      'swedish': 'Svenska',
      'spanish': 'Spanska',
      'russian': 'Ryska',
      'chinese': 'Kinesiska',
      'settings': 'INSTÄLLNINGAR',
      'appLanguage': 'APPENS SPRÅK',
      'languageHelp': 'GymRat använder mobilens språk som standard.',
      'level': 'NIVÅ',
      'days': 'DAGAR',
      'day': 'DAG',
      'xp': 'XP',
      'soon': 'SNART',
      'personalBest': 'PERSONBÄSTA',
      'newPersonalBest': 'NYTT PERSONBÄSTA',
      'levelUp': 'LEVEL UP!',
      'workoutComplete': 'TRÄNING KLAR',
      'xpEarned': 'INTJÄNAD XP',
      'streak': 'SVIT',
      'volume': 'VOLYM',
      'time': 'TID',
      'collectContinue': 'HÄMTA XP & FORTSÄTT',
      'evolutionUnlocked': 'GYMRAT-EVOLUTION UPPLÅST',
      'recordBroken': 'REKORD SLAGET',
      'powerSurging': 'KRAFTEN ÖKAR',
      'gymUpgrade': 'GYMUPPGRADERING',
      'unlocked': 'UPPLÅST',
      'tier': 'STEG',
      'upgradeDumbbellRack': 'HANTELSTÄLL I STÅL',
      'upgradeNeonLights': 'NEONBELYSNING',
      'upgradeWeightPlates': 'OLYMPISKA VIKTSKIVOR',
      'upgradePowerRack': 'POWER RACK',
      'upgradeLiftingPlatform': 'ELITPLATTFORM',
      'upgradeBanner': 'GYMRAT-KAMPFANA',
      'upgradeSpotlights': 'MÄSTARSPOTLIGHTS',
      'upgradeSpeakers': 'TUNGT LJUDSYSTEM',
      'upgradeChampionPlaque': 'MÄSTARPLAKETT',
      'upgradeCableTowers': 'ELITKABELTORN',
      'upgradeKettlebellRack': 'KETTLEBELLSTÄLL',
      'upgradeChalkStation': 'MAGNESIASTATION',
      'upgradeBattleRopes': 'BATTLE ROPES',
      'upgradePlyoBoxes': 'PLYOBOXAR',
      'upgradeWallArmor': 'GRAPHITE-VÄGGPANELER',
      'upgradeAirBike': 'AIR BIKE',
      'upgradeRower': 'RODDMASKIN',
      'upgradeProwlerSled': 'PROWLER-SLÄDE',
      'upgradeClimbingRopes': 'KLÄTTERREP',
      'upgradeLightingTruss': 'ELITBELYSNING',
      'upgradeTrophyCase': 'TROFÉMONTER',
      'upgradePunchingBag': 'TUNG BOXNINGSSÄCK',
      'upgradeLegPress': 'BENPRESS',
      'upgradeGluteHam': 'GLUTE-HAM-STATION',
      'upgradeLightningInsignia': 'GYMRAT-BLIXT',
      'upgradeMedicineBallRack': 'MEDICINBOLLSSTÄLL',
      'upgradeResistanceStation': 'MOTSTÅNDSBANDSSTATION',
      'upgradeLandmineStation': 'LANDMINE-STATION',
      'upgradeRecoveryFan': 'ÅTERHÄMTNINGSFLÄKT',
      'upgradeCompetitionPlatform': 'TÄVLINGSPLATTFORM',
      'upgradeCurvedTreadmill': 'BÖJT LÖPBAND',
      'upgradeSkiErg': 'SKIERG',
      'upgradeChainStorage': 'KEDJESTÄLL',
      'upgradeSpecialtyBars': 'SPECIALSTÄNGER',
      'upgradeChampionColumns': 'MÄSTARPELARE',
      'upgradeAtlasStones': 'ATLASSTENAR',
      'upgradeFarmerHandles': 'FARMER WALK-HANDTAG',
      'upgradeYoke': 'STRONGMAN-YOKE',
      'upgradeDustExtraction': 'MAGNESIAUTSUG',
      'upgradeChampionDisplay': 'MÄSTARMONTER',
      'upgradeDipStation': 'DIPSTATION',
      'upgradeReverseHyper': 'REVERSE HYPER',
      'upgradeLegExtension': 'BENSPARK & BENCURL',
      'upgradeCalfRaise': 'VADPRESS',
      'upgradePrestigeLighting': 'PRESTIGEBELYSNING',
      'upgradeMonolift': 'TÄVLINGS-MONOLIFT',
      'upgradeCompetitionBench': 'TÄVLINGSBÄNK',
      'upgradeDeadliftStation': 'MARKLYFTSSTATION',
      'upgradeRecoveryStation': 'ELITÅTERHÄMTNING',
      'upgradeVictoryArch': 'MÄSTARBÅGE',
    },
    'es': {
      'workout': 'Entrenamiento',
      'progress': 'Progreso',
      'history': 'Historial',
      'nutrition': 'Nutrición',
      'inventoryShop': 'Gym Armory',
      'missions': 'Misiones',
      'armoryTitle': 'GYM ARMORY',
      'armoryCollection': 'COLECCIÓN',
      'armoryStore': 'TIENDA',
      'armoryLoadError': 'No se pudo cargar Gym Armory.',
      'armoryCollectionTitle': 'TU GIMNASIO. TU LEGADO.',
      'armoryCollectionSubtitle': 'Cada mejora aquí se ha ganado entrenando.',
      'armoryUnlockedCount': 'MEJORAS DESBLOQUEADAS',
      'armoryEarnedUpgrades': 'MEJORAS DE GIMNASIO GANADAS',
      'armoryNext': 'SIGUIENTE EN NIVEL',
      'armoryComplete': 'ARMORY COMPLETA',
      'armoryVaultTitle': 'LA BÓVEDA PREMIUM',
      'armoryVaultSubtitle': 'Premium y los objetos cosméticos para tu rata aparecerán aquí desde la tienda oficial.',
      'restorePurchases': 'RESTAURAR COMPRAS',
      'armoryOwned': 'ADQUIRIDO',
      'armoryStorePreparing': 'LA BÓVEDA SE ESTÁ FORJANDO',
      'armoryStorePreparingMessage': 'Tu colección ganada está lista. Los objetos se activan al conectar los productos oficiales.',
      'armoryStoreEmpty': 'NO HAY OBJETOS EN ESTA ENTREGA',
      'armoryStoreEmptyMessage':
          'La tienda está conectada, pero no hay una oferta disponible.',
      'armoryStoreUnavailable': 'LA BÓVEDA ESTÁ DESCONECTADA',
      'armoryStoreUnavailableMessage':
          'No se pudieron cargar los objetos. Tu progreso no se ve afectado.',
      'armoryPurchaseComplete': 'Objeto desbloqueado en tu cuenta.',
      'armoryPurchaseFailed': 'No se pudo completar la compra.',
      'armoryRestoreComplete': 'Compras restauradas.',
      'armoryRestoreFailed': 'No se pudieron restaurar las compras.',
      'questBoardTitle': 'TABLÓN DE MISIONES',
      'questBoardSubtitle': 'Entrena hoy y completa tus contratos diarios.',
      'questLoadError': 'No se pudieron cargar las misiones.',
      'dailyContracts': 'CONTRATOS DIARIOS',
      'dailyContractsSubtitle': 'Se reinician cada nuevo día.',
      'weeklyCampaign': 'CAMPAÑA SEMANAL',
      'weeklyCampaignSubtitle': 'Crea impulso de lunes a domingo.',
      'questsInProgress': 'CONTRATOS EN CURSO',
      'dailyComplete': 'TABLÓN DIARIO COMPLETADO',
      'dailyCompleteMessage': 'Todos los contratos diarios están completos.',
      'questDailySession': 'RESPONDE A LA LLAMADA',
      'questDailySessionDescription': 'Completa un entrenamiento o paseo hoy.',
      'questDailyDuration': 'MANTÉN LA LÍNEA',
      'questDailyDurationDescription': 'Entrena durante 20 minutos hoy.',
      'questDailyExercises': 'DESPEJA EL SOPORTE',
      'questDailyExercisesDescription': 'Completa tres ejercicios hoy.',
      'questWeeklySessions': 'CAMPAÑA DE TRES BATALLAS',
      'questWeeklySessionsDescription': 'Completa tres sesiones esta semana.',
      'questWeeklyDuration': 'CAMPAÑA DE RESISTENCIA',
      'questWeeklyDurationDescription': 'Entrena 90 minutos esta semana.',
      'profileSettings': 'Perfil y Ajustes',
      'premium': 'GymRat Premium',
      'startWorkout': 'INICIAR ENTRENAMIENTO',
      'chooseSession': 'ELIGE TU\nSESIÓN',
      'workoutTagline': 'Entrena. Gana XP. Sube de nivel.',
      'workoutTitle': 'ENTRENAMIENTO',
      'timedWalkStreak': 'Caminata cronometrada · cuenta para tu racha',
      'customWorkout': 'ENTRENAMIENTO PERSONALIZADO',
      'customWorkoutDescription':
          'Crea tu propia sesión con toda la biblioteca de ejercicios.',
      'premiumLabel': 'PREMIUM',
      'preview': 'VISTA PREVIA',
      'startWalk': 'INICIAR CAMINATA',
      'sets': 'SERIES',
      'timedWalk': 'CAMINATA CRONOMETRADA',
      'timedWalkDescription':
          'Camina todo el tiempo que quieras. La sesión cuenta para tu racha.',
      'walkTitle': 'CAMINATA',
      'walkInProgress': 'CAMINATA EN CURSO',
      'ready': 'LISTO',
      'pause': 'PAUSAR',
      'start': 'INICIAR',
      'saving': 'GUARDANDO...',
      'finish': 'FINALIZAR',
      'exercise': 'EJERCICIO',
      'addSet': 'AÑADIR SERIE',
      'totalVolume': 'VOLUMEN TOTAL',
      'setLabel': 'SERIE',
      'rest': 'DESCANSO',
      'reps': 'REPETICIONES',
      'finishWorkout': 'FINALIZAR ENTRENAMIENTO',
      'nextExercise': 'SIGUIENTE EJERCICIO',
      'timerSettings': 'AJUSTES DEL TEMPORIZADOR',
      'save': 'GUARDAR',
      'setTimer': 'TEMPORIZADOR DE SERIE',
      'restTimer': 'TEMPORIZADOR DE DESCANSO',
      'autoLoop': 'BUCLE AUTOMÁTICO',
      'autoLoopDescription': 'Cambia automáticamente entre serie y descanso.',
      'progressTitle': 'PROGRESO',
      'progressComingSoon':
          'Los niveles, XP y la progresión llegarán próximamente.',
      'totalXp': 'XP TOTAL',
      'totalWorkouts': 'ENTRENAMIENTOS',
      'recentWorkouts': 'ENTRENAMIENTOS RECIENTES',
      'noWorkoutsYet':
          'Completa tu primer entrenamiento para iniciar tu historial.',
      'nextLevel': 'SIGUIENTE NIVEL',
      'minutesShort': 'MIN',
      'progressLoadError': 'No se pudo cargar el progreso.',
      'historyLoadError': 'No se pudo cargar el historial de entrenamiento.',
      'trainingHistory': 'HISTORIAL DE ENTRENAMIENTO',
      'combatLog': 'REGISTRO DE COMBATE',
      'records': 'RÉCORDS',
      'trainingArchive': 'ARCHIVO DE ENTRENAMIENTO',
      'trainingArchiveSubtitle': 'Cada sesión demuestra el trabajo realizado.',
      'emptyHistoryTitle': 'NO HAY SESIONES REGISTRADAS',
      'emptyHistoryMessage':
          'Completa un entrenamiento para crear la primera entrada.',
      'tapForDetails': 'TOCA PARA VER DETALLES',
      'workoutDetails': 'DETALLES DEL ENTRENAMIENTO',
      'exerciseBreakdown': 'DESGLOSE DE EJERCICIOS',
      'noExercisesRecorded': 'No hay ejercicios registrados en esta sesión.',
      'recordVault': 'SALÓN DE LOS RÉCORDS',
      'recordVaultSubtitle':
          'Ganado bajo presión. Construido repetición a repetición.',
      'recordsUnlocked': 'RÉCORDS DESBLOQUEADOS',
      'noRecordsTitle': 'AÚN NO HAY RÉCORDS',
      'noRecordsMessage': 'Tu primer resultado fija la base. Supéralo para desbloquear un récord.',
      'baseline': 'BASE',
      'previousBest': 'RÉCORD ANTERIOR',
      'totalGain': 'MEJORA TOTAL',
      'recordBreaks': 'RÉCORDS SUPERADOS',
      'language': 'Idioma',
      'systemDefault': 'Idioma del sistema',
      'english': 'Inglés',
      'swedish': 'Sueco',
      'spanish': 'Español',
      'russian': 'Ruso',
      'chinese': 'Chino',
      'settings': 'AJUSTES',
      'appLanguage': 'IDIOMA DE LA APP',
      'languageHelp': 'GymRat usa el idioma de tu teléfono por defecto.',
      'level': 'NIV',
      'days': 'DÍAS',
      'day': 'DÍA',
      'xp': 'XP',
      'soon': 'PRONTO',
      'personalBest': 'RÉCORD PERSONAL',
      'newPersonalBest': 'NUEVO RÉCORD PERSONAL',
      'levelUp': '¡SUBES DE NIVEL!',
      'workoutComplete': 'ENTRENAMIENTO COMPLETADO',
      'xpEarned': 'XP GANADA',
      'streak': 'RACHA',
      'volume': 'VOLUMEN',
      'time': 'TIEMPO',
      'collectContinue': 'RECOGER XP Y CONTINUAR',
      'evolutionUnlocked': 'EVOLUCIÓN DE GYMRAT DESBLOQUEADA',
      'recordBroken': 'RÉCORD SUPERADO',
      'powerSurging': 'EL PODER AUMENTA',
      'gymUpgrade': 'MEJORA DEL GIMNASIO',
      'unlocked': 'DESBLOQUEADO',
      'tier': 'NIVEL',
      'upgradeDumbbellRack': 'SOPORTE DE MANCUERNAS',
      'upgradeNeonLights': 'LUCES DE NEÓN',
      'upgradeWeightPlates': 'DISCOS OLÍMPICOS',
      'upgradePowerRack': 'JAULA DE POTENCIA',
      'upgradeLiftingPlatform': 'PLATAFORMA DE ÉLITE',
      'upgradeBanner': 'BANDERA DE BATALLA',
      'upgradeSpotlights': 'FOCOS DE CAMPEÓN',
      'upgradeSpeakers': 'SISTEMA DE SONIDO',
      'upgradeChampionPlaque': 'PLACA DE CAMPEÓN',
      'upgradeCableTowers': 'TORRES DE CABLE',
      'upgradeKettlebellRack': 'SOPORTE DE KETTLEBELLS',
      'upgradeChalkStation': 'ESTACIÓN DE MAGNESIA',
      'upgradeBattleRopes': 'CUERDAS DE BATALLA',
      'upgradePlyoBoxes': 'CAJONES PLIOMÉTRICOS',
      'upgradeWallArmor': 'PANELES DE GRAFITO',
      'upgradeAirBike': 'BICICLETA DE AIRE',
      'upgradeRower': 'REMO ERGOMÉTRICO',
      'upgradeProwlerSled': 'TRINEO PROWLER',
      'upgradeClimbingRopes': 'CUERDAS DE ESCALADA',
      'upgradeLightingTruss': 'ESTRUCTURA DE ILUMINACIÓN',
      'upgradeTrophyCase': 'VITRINA DE TROFEOS',
      'upgradePunchingBag': 'SACO DE BOXEO PESADO',
      'upgradeLegPress': 'PRENSA DE PIERNAS',
      'upgradeGluteHam': 'BANCO GLUTE-HAM',
      'upgradeLightningInsignia': 'INSIGNIA RELÁMPAGO GYMRAT',
      'upgradeMedicineBallRack': 'SOPORTE DE BALONES MEDICINALES',
      'upgradeResistanceStation': 'ESTACIÓN DE BANDAS',
      'upgradeLandmineStation': 'ESTACIÓN LANDMINE',
      'upgradeRecoveryFan': 'VENTILADOR DE RECUPERACIÓN',
      'upgradeCompetitionPlatform': 'PLATAFORMA DE COMPETICIÓN',
      'upgradeCurvedTreadmill': 'CINTA CURVA',
      'upgradeSkiErg': 'SKIERG',
      'upgradeChainStorage': 'SOPORTE DE CADENAS',
      'upgradeSpecialtyBars': 'BARRAS ESPECIALES',
      'upgradeChampionColumns': 'COLUMNAS DE CAMPEÓN',
      'upgradeAtlasStones': 'PIEDRAS ATLAS',
      'upgradeFarmerHandles': 'ASAS DE PASEO DEL GRANJERO',
      'upgradeYoke': 'YUGO STRONGMAN',
      'upgradeDustExtraction': 'EXTRACCIÓN DE MAGNESIA',
      'upgradeChampionDisplay': 'VITRINA DE CAMPEÓN',
      'upgradeDipStation': 'ESTACIÓN DE FONDOS',
      'upgradeReverseHyper': 'REVERSE HYPER',
      'upgradeLegExtension': 'EXTENSIÓN Y CURL DE PIERNA',
      'upgradeCalfRaise': 'MÁQUINA DE GEMELOS',
      'upgradePrestigeLighting': 'ILUMINACIÓN DE PRESTIGIO',
      'upgradeMonolift': 'MONOLIFT DE COMPETICIÓN',
      'upgradeCompetitionBench': 'BANCO DE COMPETICIÓN',
      'upgradeDeadliftStation': 'ESTACIÓN DE PESO MUERTO',
      'upgradeRecoveryStation': 'ESTACIÓN DE RECUPERACIÓN',
      'upgradeVictoryArch': 'ARCO DE LA VICTORIA',
    },
    'ru': {
      'workout': 'Тренировка',
      'progress': 'Прогресс',
      'history': 'История',
      'nutrition': 'Питание',
      'inventoryShop': 'Gym Armory',
      'missions': 'Задания',
      'armoryTitle': 'GYM ARMORY',
      'armoryCollection': 'КОЛЛЕКЦИЯ',
      'armoryStore': 'МАГАЗИН',
      'armoryLoadError': 'Не удалось загрузить Gym Armory.',
      'armoryCollectionTitle': 'ТВОЙ ЗАЛ. ТВОЁ НАСЛЕДИЕ.',
      'armoryCollectionSubtitle':
          'Каждое улучшение здесь заработано тренировками.',
      'armoryUnlockedCount': 'ОТКРЫТО УЛУЧШЕНИЙ',
      'armoryEarnedUpgrades': 'ЗАРАБОТАННЫЕ УЛУЧШЕНИЯ ЗАЛА',
      'armoryNext': 'СЛЕДУЮЩЕЕ НА УРОВНЕ',
      'armoryComplete': 'АРСЕНАЛ СОБРАН',
      'armoryVaultTitle': 'ПРЕМИАЛЬНОЕ ХРАНИЛИЩЕ',
      'armoryVaultSubtitle': 'Premium и косметика для крысы появятся здесь из официального магазина.',
      'restorePurchases': 'ВОССТАНОВИТЬ ПОКУПКИ',
      'armoryOwned': 'КУПЛЕНО',
      'armoryStorePreparing': 'ХРАНИЛИЩЕ СОЗДАЁТСЯ',
      'armoryStorePreparingMessage': 'Заработанная коллекция готова. Товары появятся после подключения официальных продуктов.',
      'armoryStoreEmpty': 'В ЭТОЙ ПОСТАВКЕ НЕТ ТОВАРОВ',
      'armoryStoreEmptyMessage':
          'Магазин подключён, но актуального предложения нет.',
      'armoryStoreUnavailable': 'ХРАНИЛИЩЕ НЕ В СЕТИ',
      'armoryStoreUnavailableMessage':
          'Не удалось загрузить товары. Прогресс тренировок не затронут.',
      'armoryPurchaseComplete': 'Предмет открыт в вашей учётной записи.',
      'armoryPurchaseFailed': 'Не удалось завершить покупку.',
      'armoryRestoreComplete': 'Покупки восстановлены.',
      'armoryRestoreFailed': 'Не удалось восстановить покупки.',
      'questBoardTitle': 'ДОСКА ЗАДАНИЙ',
      'questBoardSubtitle': 'Тренируйся сегодня и выполни дневные задания.',
      'questLoadError': 'Не удалось загрузить задания.',
      'dailyContracts': 'ЕЖЕДНЕВНЫЕ ЗАДАНИЯ',
      'dailyContractsSubtitle': 'Обновляются каждый новый день.',
      'weeklyCampaign': 'НЕДЕЛЬНАЯ КАМПАНИЯ',
      'weeklyCampaignSubtitle': 'Набирай темп с понедельника по воскресенье.',
      'questsInProgress': 'ЗАДАНИЯ В ПРОЦЕССЕ',
      'dailyComplete': 'ДНЕВНАЯ ДОСКА ЗАКРЫТА',
      'dailyCompleteMessage': 'Все ежедневные задания выполнены.',
      'questDailySession': 'ПРИМИ ВЫЗОВ',
      'questDailySessionDescription':
          'Заверши тренировку или прогулку сегодня.',
      'questDailyDuration': 'ДЕРЖИ РУБЕЖ',
      'questDailyDurationDescription': 'Тренируйся 20 минут сегодня.',
      'questDailyExercises': 'ОЧИСТИ СТОЙКУ',
      'questDailyExercisesDescription': 'Выполни три упражнения сегодня.',
      'questWeeklySessions': 'КАМПАНИЯ ТРЁХ БИТВ',
      'questWeeklySessionsDescription': 'Заверши три занятия на этой неделе.',
      'questWeeklyDuration': 'КАМПАНИЯ ВЫНОСЛИВОСТИ',
      'questWeeklyDurationDescription': 'Тренируйся 90 минут на этой неделе.',
      'profileSettings': 'Профиль и Настройки',
      'premium': 'GymRat Premium',
      'startWorkout': 'НАЧАТЬ ТРЕНИРОВКУ',
      'chooseSession': 'ВЫБЕРИ\nТРЕНИРОВКУ',
      'workoutTagline': 'Тренируйся. Получай XP. Повышай уровень.',
      'workoutTitle': 'ТРЕНИРОВКА',
      'timedWalkStreak': 'Прогулка по времени · учитывается в серии',
      'customWorkout': 'СВОЯ ТРЕНИРОВКА',
      'customWorkoutDescription':
          'Создай свою тренировку из полной библиотеки упражнений.',
      'premiumLabel': 'ПРЕМИУМ',
      'preview': 'ПРЕДПРОСМОТР',
      'startWalk': 'НАЧАТЬ ПРОГУЛКУ',
      'sets': 'ПОДХОДА',
      'timedWalk': 'ПРОГУЛКА ПО ВРЕМЕНИ',
      'timedWalkDescription':
          'Гуляй сколько хочешь. Тренировка учитывается в серии.',
      'walkTitle': 'ПРОГУЛКА',
      'walkInProgress': 'ПРОГУЛКА ИДЁТ',
      'ready': 'ГОТОВО',
      'pause': 'ПАУЗА',
      'start': 'НАЧАТЬ',
      'saving': 'СОХРАНЕНИЕ...',
      'finish': 'ЗАВЕРШИТЬ',
      'exercise': 'УПРАЖНЕНИЕ',
      'addSet': 'ДОБАВИТЬ ПОДХОД',
      'totalVolume': 'ОБЩИЙ ОБЪЁМ',
      'setLabel': 'ПОДХОД',
      'rest': 'ОТДЫХ',
      'reps': 'ПОВТОРЫ',
      'finishWorkout': 'ЗАВЕРШИТЬ ТРЕНИРОВКУ',
      'nextExercise': 'СЛЕДУЮЩЕЕ УПРАЖНЕНИЕ',
      'timerSettings': 'НАСТРОЙКИ ТАЙМЕРА',
      'save': 'СОХРАНИТЬ',
      'setTimer': 'ТАЙМЕР ПОДХОДА',
      'restTimer': 'ТАЙМЕР ОТДЫХА',
      'autoLoop': 'АВТОПЕРЕКЛЮЧЕНИЕ',
      'autoLoopDescription': 'Автоматически переключать подход и отдых.',
      'progressTitle': 'ПРОГРЕСС',
      'progressComingSoon': 'Уровни, XP и развитие появятся позже.',
      'totalXp': 'ВСЕГО XP',
      'totalWorkouts': 'ТРЕНИРОВКИ',
      'recentWorkouts': 'ПОСЛЕДНИЕ ТРЕНИРОВКИ',
      'noWorkoutsYet': 'Завершите первую тренировку, чтобы начать историю.',
      'nextLevel': 'СЛЕДУЮЩИЙ УРОВЕНЬ',
      'minutesShort': 'МИН',
      'progressLoadError': 'Не удалось загрузить прогресс.',
      'historyLoadError': 'Не удалось загрузить историю тренировок.',
      'trainingHistory': 'ИСТОРИЯ ТРЕНИРОВОК',
      'combatLog': 'БОЕВОЙ ЖУРНАЛ',
      'records': 'РЕКОРДЫ',
      'trainingArchive': 'АРХИВ ТРЕНИРОВОК',
      'trainingArchiveSubtitle':
          'Каждая тренировка подтверждает проделанную работу.',
      'emptyHistoryTitle': 'ТРЕНИРОВОК ПОКА НЕТ',
      'emptyHistoryMessage':
          'Завершите тренировку, чтобы создать первую запись.',
      'tapForDetails': 'НАЖМИТЕ ДЛЯ ПОДРОБНОСТЕЙ',
      'workoutDetails': 'ДЕТАЛИ ТРЕНИРОВКИ',
      'exerciseBreakdown': 'УПРАЖНЕНИЯ',
      'noExercisesRecorded': 'Для этой тренировки упражнения не записаны.',
      'recordVault': 'ЗАЛ РЕКОРДОВ',
      'recordVaultSubtitle':
          'Заработано под нагрузкой. Повторение за повторением.',
      'recordsUnlocked': 'ОТКРЫТО РЕКОРДОВ',
      'noRecordsTitle': 'РЕКОРДОВ ПОКА НЕТ',
      'noRecordsMessage': 'Первый результат задаёт базу. Превзойдите его, чтобы открыть рекорд.',
      'baseline': 'БАЗА',
      'previousBest': 'ПРЕДЫДУЩИЙ РЕКОРД',
      'totalGain': 'ОБЩИЙ ПРИРОСТ',
      'recordBreaks': 'ПОБИТО РЕКОРДОВ',
      'language': 'Язык',
      'systemDefault': 'Язык системы',
      'english': 'Английский',
      'swedish': 'Шведский',
      'spanish': 'Испанский',
      'russian': 'Русский',
      'chinese': 'Китайский',
      'settings': 'НАСТРОЙКИ',
      'appLanguage': 'ЯЗЫК ПРИЛОЖЕНИЯ',
      'languageHelp': 'GymRat использует язык телефона по умолчанию.',
      'level': 'УР',
      'days': 'ДНЕЙ',
      'day': 'ДЕНЬ',
      'xp': 'XP',
      'soon': 'СКОРО',
      'personalBest': 'ЛИЧНЫЙ РЕКОРД',
      'newPersonalBest': 'НОВЫЙ ЛИЧНЫЙ РЕКОРД',
      'levelUp': 'НОВЫЙ УРОВЕНЬ!',
      'workoutComplete': 'ТРЕНИРОВКА ЗАВЕРШЕНА',
      'xpEarned': 'ПОЛУЧЕНО XP',
      'streak': 'СЕРИЯ',
      'volume': 'ОБЪЁМ',
      'time': 'ВРЕМЯ',
      'collectContinue': 'ЗАБРАТЬ XP И ПРОДОЛЖИТЬ',
      'evolutionUnlocked': 'ЭВОЛЮЦИЯ GYMRAT РАЗБЛОКИРОВАНА',
      'recordBroken': 'РЕКОРД ПОБИТ',
      'powerSurging': 'СИЛА РАСТЁТ',
      'gymUpgrade': 'УЛУЧШЕНИЕ ЗАЛА',
      'unlocked': 'РАЗБЛОКИРОВАНО',
      'tier': 'УРОВЕНЬ',
      'upgradeDumbbellRack': 'СТОЙКА С ГАНТЕЛЯМИ',
      'upgradeNeonLights': 'НЕОНОВОЕ ОСВЕЩЕНИЕ',
      'upgradeWeightPlates': 'ОЛИМПИЙСКИЕ ДИСКИ',
      'upgradePowerRack': 'СИЛОВАЯ РАМА',
      'upgradeLiftingPlatform': 'ЭЛИТНАЯ ПОМОСТ-ПЛАТФОРМА',
      'upgradeBanner': 'БОЕВОЕ ЗНАМЯ GYMRAT',
      'upgradeSpotlights': 'ЧЕМПИОНСКИЕ ПРОЖЕКТОРЫ',
      'upgradeSpeakers': 'МОЩНАЯ АУДИОСИСТЕМА',
      'upgradeChampionPlaque': 'ТАБЛИЧКА ЧЕМПИОНА',
      'upgradeCableTowers': 'КАБЕЛЬНЫЕ БАШНИ',
      'upgradeKettlebellRack': 'СТОЙКА С ГИРЯМИ',
      'upgradeChalkStation': 'СТАНЦИЯ ДЛЯ МАГНЕЗИИ',
      'upgradeBattleRopes': 'ТРЕНИРОВОЧНЫЕ КАНАТЫ',
      'upgradePlyoBoxes': 'ПЛИОМЕТРИЧЕСКИЕ ТУМБЫ',
      'upgradeWallArmor': 'ГРАФИТОВЫЕ ПАНЕЛИ',
      'upgradeAirBike': 'ВОЗДУШНЫЙ ВЕЛОТРЕНАЖЁР',
      'upgradeRower': 'ГРЕБНОЙ ТРЕНАЖЁР',
      'upgradeProwlerSled': 'СИЛОВЫЕ САНИ',
      'upgradeClimbingRopes': 'КАНАТЫ ДЛЯ ЛАЗАНИЯ',
      'upgradeLightingTruss': 'ЭЛИТНАЯ СВЕТОВАЯ ФЕРМА',
      'upgradeTrophyCase': 'ВИТРИНА С ТРОФЕЯМИ',
      'upgradePunchingBag': 'ТЯЖЁЛАЯ ГРУША',
      'upgradeLegPress': 'ЖИМ НОГАМИ',
      'upgradeGluteHam': 'СТАНЦИЯ GLUTE-HAM',
      'upgradeLightningInsignia': 'ЗНАК-МОЛНИЯ GYMRAT',
      'upgradeMedicineBallRack': 'СТОЙКА С МЕДБОЛАМИ',
      'upgradeResistanceStation': 'СТАНЦИЯ С ЭСПАНДЕРАМИ',
      'upgradeLandmineStation': 'СТАНЦИЯ LANDMINE',
      'upgradeRecoveryFan': 'ВЕНТИЛЯТОР ВОССТАНОВЛЕНИЯ',
      'upgradeCompetitionPlatform': 'СОРЕВНОВАТЕЛЬНЫЙ ПОМОСТ',
      'upgradeCurvedTreadmill': 'ИЗОГНУТАЯ БЕГОВАЯ ДОРОЖКА',
      'upgradeSkiErg': 'SKIERG',
      'upgradeChainStorage': 'СТОЙКА ДЛЯ ЦЕПЕЙ',
      'upgradeSpecialtyBars': 'СПЕЦИАЛЬНЫЕ ГРИФЫ',
      'upgradeChampionColumns': 'ЧЕМПИОНСКИЕ КОЛОННЫ',
      'upgradeAtlasStones': 'КАМНИ АТЛАСА',
      'upgradeFarmerHandles': 'РУКОЯТИ ФЕРМЕРА',
      'upgradeYoke': 'СИЛОВАЯ РАМА-YOKE',
      'upgradeDustExtraction': 'ВЫТЯЖКА ДЛЯ МАГНЕЗИИ',
      'upgradeChampionDisplay': 'ЧЕМПИОНСКАЯ ВИТРИНА',
      'upgradeDipStation': 'БРУСЬЯ',
      'upgradeReverseHyper': 'REVERSE HYPER',
      'upgradeLegExtension': 'РАЗГИБАНИЕ И СГИБАНИЕ НОГ',
      'upgradeCalfRaise': 'ТРЕНАЖЁР ДЛЯ ИКР',
      'upgradePrestigeLighting': 'ПРЕСТИЖНОЕ ОСВЕЩЕНИЕ',
      'upgradeMonolift': 'MONOLIFT',
      'upgradeCompetitionBench': 'СОРЕВНОВАТЕЛЬНАЯ СКАМЬЯ',
      'upgradeDeadliftStation': 'СТАНЦИЯ СТАНОВОЙ ТЯГИ',
      'upgradeRecoveryStation': 'СТАНЦИЯ ВОССТАНОВЛЕНИЯ',
      'upgradeVictoryArch': 'АРКА ПОБЕДЫ',
    },
    'zh': {
      'workout': '训练',
      'progress': '进度',
      'history': '历史',
      'nutrition': '营养',
      'inventoryShop': 'Gym Armory',
      'missions': '任务',
      'armoryTitle': 'GYM ARMORY',
      'armoryCollection': '收藏',
      'armoryStore': '商店',
      'armoryLoadError': '无法加载 Gym Armory。',
      'armoryCollectionTitle': '你的健身房。你的传奇。',
      'armoryCollectionSubtitle': '这里的每项升级都通过训练赢得。',
      'armoryUnlockedCount': '已解锁升级',
      'armoryEarnedUpgrades': '已赢得的健身房升级',
      'armoryNext': '下次解锁等级',
      'armoryComplete': '军械库已集齐',
      'armoryVaultTitle': '高级宝库',
      'armoryVaultSubtitle': 'Premium 和健身鼠外观道具将在官方商店接入后显示于此。',
      'restorePurchases': '恢复购买',
      'armoryOwned': '已拥有',
      'armoryStorePreparing': '宝库正在锻造',
      'armoryStorePreparingMessage': '你赢得的收藏已就绪。官方商品接入后将启用商店道具。',
      'armoryStoreEmpty': '本次上新暂无道具',
      'armoryStoreEmptyMessage': '商店已连接，但目前没有可用商品。',
      'armoryStoreUnavailable': '宝库暂时离线',
      'armoryStoreUnavailableMessage': '无法加载商店道具。你的训练进度不受影响。',
      'armoryPurchaseComplete': '道具已解锁到你的账户。',
      'armoryPurchaseFailed': '无法完成购买。',
      'armoryRestoreComplete': '购买已恢复。',
      'armoryRestoreFailed': '无法恢复购买。',
      'questBoardTitle': '任务板',
      'questBoardSubtitle': '今天训练并完成每日契约。',
      'questLoadError': '无法加载任务。',
      'dailyContracts': '每日契约',
      'dailyContractsSubtitle': '每天重新开始。',
      'weeklyCampaign': '每周战役',
      'weeklyCampaignSubtitle': '从周一到周日积累势头。',
      'questsInProgress': '契约进行中',
      'dailyComplete': '每日任务已清空',
      'dailyCompleteMessage': '所有每日契约均已完成。',
      'questDailySession': '响应召唤',
      'questDailySessionDescription': '今天完成一次训练或步行。',
      'questDailyDuration': '坚守阵线',
      'questDailyDurationDescription': '今天训练20分钟。',
      'questDailyExercises': '清空器械架',
      'questDailyExercisesDescription': '今天完成三个动作。',
      'questWeeklySessions': '三战战役',
      'questWeeklySessionsDescription': '本周完成三次训练。',
      'questWeeklyDuration': '耐力战役',
      'questWeeklyDurationDescription': '本周训练90分钟。',
      'profileSettings': '个人资料与设置',
      'premium': 'GymRat Premium',
      'startWorkout': '开始训练',
      'chooseSession': '选择你的\n训练',
      'workoutTagline': '训练。赚取 XP。提升等级。',
      'workoutTitle': '训练',
      'timedWalkStreak': '计时步行 · 计入连续记录',
      'customWorkout': '自定义训练',
      'customWorkoutDescription': '从完整动作库中创建自己的训练。',
      'premiumLabel': '高级版',
      'preview': '预览',
      'startWalk': '开始步行',
      'sets': '组',
      'timedWalk': '计时步行',
      'timedWalkDescription': '想走多久都可以。本次训练会计入连续记录。',
      'walkTitle': '步行',
      'walkInProgress': '步行进行中',
      'ready': '准备就绪',
      'pause': '暂停',
      'start': '开始',
      'saving': '正在保存...',
      'finish': '完成',
      'exercise': '动作',
      'addSet': '添加一组',
      'totalVolume': '总训练量',
      'setLabel': '组',
      'rest': '休息',
      'reps': '次数',
      'finishWorkout': '完成训练',
      'nextExercise': '下一个动作',
      'timerSettings': '计时器设置',
      'save': '保存',
      'setTimer': '组间计时',
      'restTimer': '休息计时',
      'autoLoop': '自动循环',
      'autoLoopDescription': '在训练组和休息之间自动切换。',
      'progressTitle': '进度',
      'progressComingSoon': '等级、XP 和成长功能即将推出。',
      'totalXp': 'XP 总计',
      'totalWorkouts': '训练次数',
      'recentWorkouts': '最近训练',
      'noWorkoutsYet': '完成第一次训练即可开始记录。',
      'nextLevel': '下一级',
      'minutesShort': '分钟',
      'progressLoadError': '无法加载进度。',
      'historyLoadError': '无法加载训练历史。',
      'trainingHistory': '训练历史',
      'combatLog': '战斗日志',
      'records': '纪录',
      'trainingArchive': '训练档案',
      'trainingArchiveSubtitle': '每一次训练都是努力的证明。',
      'emptyHistoryTitle': '尚无训练记录',
      'emptyHistoryMessage': '完成一次训练，写下第一条记录。',
      'tapForDetails': '点击查看详情',
      'workoutDetails': '训练详情',
      'exerciseBreakdown': '动作明细',
      'noExercisesRecorded': '本次训练没有记录动作。',
      'recordVault': '纪录殿堂',
      'recordVaultSubtitle': '在压力中赢得，一次次重复铸就。',
      'recordsUnlocked': '已解锁纪录',
      'noRecordsTitle': '尚无纪录',
      'noRecordsMessage': '第一次成绩会成为基准。超越它即可解锁纪录。',
      'baseline': '基准',
      'previousBest': '上次最佳',
      'totalGain': '总提升',
      'recordBreaks': '打破纪录次数',
      'language': '语言',
      'systemDefault': '系统默认',
      'english': '英语',
      'swedish': '瑞典语',
      'spanish': '西班牙语',
      'russian': '俄语',
      'chinese': '中文',
      'settings': '设置',
      'appLanguage': '应用语言',
      'languageHelp': 'GymRat 默认使用手机的系统语言。',
      'level': '等级',
      'days': '天',
      'day': '天',
      'xp': 'XP',
      'soon': '即将推出',
      'personalBest': '个人最佳',
      'newPersonalBest': '新的个人最佳',
      'levelUp': '升级！',
      'workoutComplete': '训练完成',
      'xpEarned': '获得 XP',
      'streak': '连续',
      'volume': '训练量',
      'time': '时间',
      'collectContinue': '领取 XP 并继续',
      'evolutionUnlocked': 'GYMRAT 进化已解锁',
      'recordBroken': '打破纪录',
      'powerSurging': '力量提升中',
      'gymUpgrade': '健身房升级',
      'unlocked': '已解锁',
      'tier': '等级',
      'upgradeDumbbellRack': '钢制哑铃架',
      'upgradeNeonLights': '霓虹能量灯',
      'upgradeWeightPlates': '奥林匹克杠铃片',
      'upgradePowerRack': '力量训练架',
      'upgradeLiftingPlatform': '精英举重台',
      'upgradeBanner': 'GYMRAT 战旗',
      'upgradeSpotlights': '冠军聚光灯',
      'upgradeSpeakers': '重型音响系统',
      'upgradeChampionPlaque': '冠军铭牌',
      'upgradeCableTowers': '双侧绳索训练塔',
      'upgradeKettlebellRack': '壶铃架',
      'upgradeChalkStation': '镁粉站',
      'upgradeBattleRopes': '战绳',
      'upgradePlyoBoxes': '跳箱',
      'upgradeWallArmor': '石墨墙板',
      'upgradeAirBike': '风阻单车',
      'upgradeRower': '划船机',
      'upgradeProwlerSled': '力量雪橇',
      'upgradeClimbingRopes': '攀爬绳',
      'upgradeLightingTruss': '精英灯光桁架',
      'upgradeTrophyCase': '奖杯陈列柜',
      'upgradePunchingBag': '重型沙袋',
      'upgradeLegPress': '腿举机',
      'upgradeGluteHam': '臀腿训练架',
      'upgradeLightningInsignia': 'GYMRAT 闪电徽章',
      'upgradeMedicineBallRack': '药球架',
      'upgradeResistanceStation': '弹力带训练站',
      'upgradeLandmineStation': '地雷架',
      'upgradeRecoveryFan': '恢复风扇',
      'upgradeCompetitionPlatform': '竞赛举重台',
      'upgradeCurvedTreadmill': '弧形跑步机',
      'upgradeSkiErg': '滑雪机',
      'upgradeChainStorage': '链条架',
      'upgradeSpecialtyBars': '特种杠铃架',
      'upgradeChampionColumns': '冠军立柱',
      'upgradeAtlasStones': '阿特拉斯巨石',
      'upgradeFarmerHandles': '农夫走手柄',
      'upgradeYoke': '强人轭架',
      'upgradeDustExtraction': '镁粉除尘系统',
      'upgradeChampionDisplay': '冠军陈列柜',
      'upgradeDipStation': '双杠训练站',
      'upgradeReverseHyper': '反向挺身机',
      'upgradeLegExtension': '腿屈伸训练机',
      'upgradeCalfRaise': '提踵机',
      'upgradePrestigeLighting': '荣耀灯光',
      'upgradeMonolift': '单举架',
      'upgradeCompetitionBench': '比赛卧推架',
      'upgradeDeadliftStation': '硬拉维护站',
      'upgradeRecoveryStation': '恢复站',
      'upgradeVictoryArch': '胜利拱门',
    },
  };
  String t(String key) {
    final language = _values.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'en';
    return _values[language]?[key] ?? _values['en']![key] ?? key;
  }
}

class _GymRatLocalizationsDelegate
    extends LocalizationsDelegate<GymRatLocalizations> {
  const _GymRatLocalizationsDelegate();
  @override
  bool isSupported(Locale locale) =>
      ['en', 'sv', 'es', 'ru', 'zh'].contains(locale.languageCode);
  @override
  Future<GymRatLocalizations> load(Locale locale) async =>
      GymRatLocalizations(locale);
  @override
  bool shouldReload(_GymRatLocalizationsDelegate old) => false;
}

extension GymRatText on BuildContext {
  GymRatLocalizations get tr => GymRatLocalizations.of(this);
}
